name: Keep Node.js Backend Alive
on:
  schedule:
    - cron: '*/5 * * * *'  # A cada 5 minutos
jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Backend
        run: |
          curl -s "https://cotabrasil.onrender.com/api/health" > /dev/null
          echo "Backend acordado!"