name: Keep Render Alive  
on:  
  schedule:  
    - cron: '*/5 * * * *'  # A cada 5 minutos  
jobs:  
  ping:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Access site  
        run: curl -s https://cotabrasil.onrender.com > /dev/null  